/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdeaHubRouteImport } from './routes/idea-hub'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTreinamentosRouteImport } from './routes/app.treinamentos'
import { Route as AppReunioesRouteImport } from './routes/app.reunioes'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppProjetosRouteImport } from './routes/app.projetos'
import { Route as AppPostagensRouteImport } from './routes/app.postagens'
import { Route as AppEventosRouteImport } from './routes/app.eventos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppChamadosRouteImport } from './routes/app.chamados'
import { Route as AppCampanhasRouteImport } from './routes/app.campanhas'
import { Route as AppArquivosRouteImport } from './routes/app.arquivos'
import { Route as AppAprovacoesRouteImport } from './routes/app.aprovacoes'
import { Route as AppAcoesRouteImport } from './routes/app.acoes'
import { Route as AppProjetosIdRouteImport } from './routes/app.projetos.$id'
import { Route as AppClientesIdRouteImport } from './routes/app.clientes.$id'
import { Route as AppAprovacoesIdRouteImport } from './routes/app.aprovacoes.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaHubRoute = IdeaHubRouteImport.update({
  id: '/idea-hub',
  path: '/idea-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinamentosRoute = AppTreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppReunioesRoute = AppReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppPostagensRoute = AppPostagensRouteImport.update({
  id: '/postagens',
  path: '/postagens',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppChamadosRoute = AppChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppArquivosRoute = AppArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AppRoute,
} as any)
const AppAprovacoesRoute = AppAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAcoesRoute = AppAcoesRouteImport.update({
  id: '/acoes',
  path: '/acoes',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosIdRoute = AppProjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjetosRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppAprovacoesIdRoute = AppAprovacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAprovacoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/idea-hub': typeof IdeaHubRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/app/acoes': typeof AppAcoesRoute
  '/app/aprovacoes': typeof AppAprovacoesRouteWithChildren
  '/app/arquivos': typeof AppArquivosRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/chamados': typeof AppChamadosRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/postagens': typeof AppPostagensRoute
  '/app/projetos': typeof AppProjetosRouteWithChildren
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/reunioes': typeof AppReunioesRoute
  '/app/treinamentos': typeof AppTreinamentosRoute
  '/app/': typeof AppIndexRoute
  '/app/aprovacoes/$id': typeof AppAprovacoesIdRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/idea-hub': typeof IdeaHubRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/app/acoes': typeof AppAcoesRoute
  '/app/aprovacoes': typeof AppAprovacoesRouteWithChildren
  '/app/arquivos': typeof AppArquivosRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/chamados': typeof AppChamadosRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/postagens': typeof AppPostagensRoute
  '/app/projetos': typeof AppProjetosRouteWithChildren
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/reunioes': typeof AppReunioesRoute
  '/app/treinamentos': typeof AppTreinamentosRoute
  '/app': typeof AppIndexRoute
  '/app/aprovacoes/$id': typeof AppAprovacoesIdRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/idea-hub': typeof IdeaHubRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/app/acoes': typeof AppAcoesRoute
  '/app/aprovacoes': typeof AppAprovacoesRouteWithChildren
  '/app/arquivos': typeof AppArquivosRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/chamados': typeof AppChamadosRoute
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/eventos': typeof AppEventosRoute
  '/app/postagens': typeof AppPostagensRoute
  '/app/projetos': typeof AppProjetosRouteWithChildren
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/reunioes': typeof AppReunioesRoute
  '/app/treinamentos': typeof AppTreinamentosRoute
  '/app/': typeof AppIndexRoute
  '/app/aprovacoes/$id': typeof AppAprovacoesIdRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contato'
    | '/diagnostico'
    | '/idea-hub'
    | '/login'
    | '/materiais'
    | '/servicos'
    | '/sobre'
    | '/app/acoes'
    | '/app/aprovacoes'
    | '/app/arquivos'
    | '/app/campanhas'
    | '/app/chamados'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/eventos'
    | '/app/postagens'
    | '/app/projetos'
    | '/app/relatorios'
    | '/app/reunioes'
    | '/app/treinamentos'
    | '/app/'
    | '/app/aprovacoes/$id'
    | '/app/clientes/$id'
    | '/app/projetos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/diagnostico'
    | '/idea-hub'
    | '/login'
    | '/materiais'
    | '/servicos'
    | '/sobre'
    | '/app/acoes'
    | '/app/aprovacoes'
    | '/app/arquivos'
    | '/app/campanhas'
    | '/app/chamados'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/eventos'
    | '/app/postagens'
    | '/app/projetos'
    | '/app/relatorios'
    | '/app/reunioes'
    | '/app/treinamentos'
    | '/app'
    | '/app/aprovacoes/$id'
    | '/app/clientes/$id'
    | '/app/projetos/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contato'
    | '/diagnostico'
    | '/idea-hub'
    | '/login'
    | '/materiais'
    | '/servicos'
    | '/sobre'
    | '/app/acoes'
    | '/app/aprovacoes'
    | '/app/arquivos'
    | '/app/campanhas'
    | '/app/chamados'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/eventos'
    | '/app/postagens'
    | '/app/projetos'
    | '/app/relatorios'
    | '/app/reunioes'
    | '/app/treinamentos'
    | '/app/'
    | '/app/aprovacoes/$id'
    | '/app/clientes/$id'
    | '/app/projetos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  IdeaHubRoute: typeof IdeaHubRoute
  LoginRoute: typeof LoginRoute
  MateriaisRoute: typeof MateriaisRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea-hub': {
      id: '/idea-hub'
      path: '/idea-hub'
      fullPath: '/idea-hub'
      preLoaderRoute: typeof IdeaHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinamentos': {
      id: '/app/treinamentos'
      path: '/treinamentos'
      fullPath: '/app/treinamentos'
      preLoaderRoute: typeof AppTreinamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reunioes': {
      id: '/app/reunioes'
      path: '/reunioes'
      fullPath: '/app/reunioes'
      preLoaderRoute: typeof AppReunioesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/postagens': {
      id: '/app/postagens'
      path: '/postagens'
      fullPath: '/app/postagens'
      preLoaderRoute: typeof AppPostagensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/eventos': {
      id: '/app/eventos'
      path: '/eventos'
      fullPath: '/app/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chamados': {
      id: '/app/chamados'
      path: '/chamados'
      fullPath: '/app/chamados'
      preLoaderRoute: typeof AppChamadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/arquivos': {
      id: '/app/arquivos'
      path: '/arquivos'
      fullPath: '/app/arquivos'
      preLoaderRoute: typeof AppArquivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprovacoes': {
      id: '/app/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/app/aprovacoes'
      preLoaderRoute: typeof AppAprovacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/acoes': {
      id: '/app/acoes'
      path: '/acoes'
      fullPath: '/app/acoes'
      preLoaderRoute: typeof AppAcoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos/$id': {
      id: '/app/projetos/$id'
      path: '/$id'
      fullPath: '/app/projetos/$id'
      preLoaderRoute: typeof AppProjetosIdRouteImport
      parentRoute: typeof AppProjetosRoute
    }
    '/app/clientes/$id': {
      id: '/app/clientes/$id'
      path: '/$id'
      fullPath: '/app/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/app/aprovacoes/$id': {
      id: '/app/aprovacoes/$id'
      path: '/$id'
      fullPath: '/app/aprovacoes/$id'
      preLoaderRoute: typeof AppAprovacoesIdRouteImport
      parentRoute: typeof AppAprovacoesRoute
    }
  }
}

interface AppAprovacoesRouteChildren {
  AppAprovacoesIdRoute: typeof AppAprovacoesIdRoute
}

const AppAprovacoesRouteChildren: AppAprovacoesRouteChildren = {
  AppAprovacoesIdRoute: AppAprovacoesIdRoute,
}

const AppAprovacoesRouteWithChildren = AppAprovacoesRoute._addFileChildren(
  AppAprovacoesRouteChildren,
)

interface AppClientesRouteChildren {
  AppClientesIdRoute: typeof AppClientesIdRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesIdRoute: AppClientesIdRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppProjetosRouteChildren {
  AppProjetosIdRoute: typeof AppProjetosIdRoute
}

const AppProjetosRouteChildren: AppProjetosRouteChildren = {
  AppProjetosIdRoute: AppProjetosIdRoute,
}

const AppProjetosRouteWithChildren = AppProjetosRoute._addFileChildren(
  AppProjetosRouteChildren,
)

interface AppRouteChildren {
  AppAcoesRoute: typeof AppAcoesRoute
  AppAprovacoesRoute: typeof AppAprovacoesRouteWithChildren
  AppArquivosRoute: typeof AppArquivosRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppChamadosRoute: typeof AppChamadosRoute
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEventosRoute: typeof AppEventosRoute
  AppPostagensRoute: typeof AppPostagensRoute
  AppProjetosRoute: typeof AppProjetosRouteWithChildren
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppReunioesRoute: typeof AppReunioesRoute
  AppTreinamentosRoute: typeof AppTreinamentosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcoesRoute: AppAcoesRoute,
  AppAprovacoesRoute: AppAprovacoesRouteWithChildren,
  AppArquivosRoute: AppArquivosRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppChamadosRoute: AppChamadosRoute,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEventosRoute: AppEventosRoute,
  AppPostagensRoute: AppPostagensRoute,
  AppProjetosRoute: AppProjetosRouteWithChildren,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppReunioesRoute: AppReunioesRoute,
  AppTreinamentosRoute: AppTreinamentosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContatoRoute: ContatoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  IdeaHubRoute: IdeaHubRoute,
  LoginRoute: LoginRoute,
  MateriaisRoute: MateriaisRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
